backups.php: Support restoring kopia snapshots
Signed-off-by: Tobias Knöppler <6317548+theCalcaholic@users.noreply.github.com>

diff --git a/bin/kopia-restore b/bin/kopia-restore
--- a/bin/kopia-restore
+++ b/bin/kopia-restore
@@ -4,13 +4,36 @@ set -e
 
 source /usr/local/etc/library.sh
 
-REPOSITORY="${1?}"
-REPOSITORY_PASSWORD="${2?}"
-SNAPSHOT_ID="${3?}"
+SNAPSHOT_ID="${1?}"
+REPOSITORY="${2}"
+REPOSITORY_PASSWORD="${3}"
 
-data_dir="$(get_nc_config_value datadirectory)"
-docker_args=()
-kopia_args=()
+data_dir="$(get_nc_config_value datadirectory || echo '/opt/ncdata/data')"
+kopia_flags=(--config-file=/usr/local/etc/kopia/restore.config --log-dir="/var/log/kopia" --no-persist-credentials)
+kopia_repo_args=()
+[[ -z "$REPOSITORY" ]] && ! [[ -f /usr/local/etc/kopia/repository.config ]] && {
+  echo "REPOSITORY not set and no repository config found!"
+  exit 1
+}
+if [[ -z "$REPOSITORY" ]]
+then
+  config_path="/usr/local/etc/kopia/repository.config"
+  repo_type="$(jq -er '.storage.type' "${config_path}")"
+  if [[ "$repo_type" == "filesystem" ]]
+  then
+    echo "REPOSITORY not set. Attempting to read value from kopia ncp app"
+    REPOSITORY="$(find_app_param kopia DESTINATION)"
+  elif [[ "$repo_type" == "sftp" ]]
+  then
+    sftp_user="$(jq -er '.storage.config.user' "${config_path}")"
+    sftp_host="$(jq -er '.storage.config.host' "${config_path}")"
+    sftp_path="$(jq -er '.storage.config.path' "${config_path}")"
+    REPOSITORY="${sftp_user}@${sftp_host}:${sftp_path}"
+  else
+    echo "Unsupported storage type '${repo_type}!"
+    exit 1
+  fi
+fi
 if [[ "$REPOSITORY" =~ .*'@'.*':'.* ]]
 then
   repo_type="sftp"
@@ -19,26 +42,24 @@ then
   sftp_host="${sftp_host%:*}"
   repo_path="${REPOSITORY#*:}"
   ssh -o "BatchMode=yes" "${sftp_user}@${sftp_host}" || { echo "SSH non-interactive not properly configured"; return 1; }
-  kopia_args=(--host "${sftp_host}" --user "${sftp_user}" --path "${repo_path}")
+  kopia_repo_args=(--host "${sftp_host}" --user "${sftp_user}" --path "${repo_path}")
 else
   repo_type="filesystem"
   repo_path="${REPOSITORY}"
   docker_args=(-v "${repo_path}:/repository")
-  kopia_args=(--path "/repository")
+  kopia_repo_args=(--path "/repository")
 fi
+
 [[ -z "${REPOSITORY_PASSWORD}" ]] && [[ -f /usr/local/etc/kopia/password ]] && \
   REPOSITORY_PASSWORD="$(cat /usr/local/etc/kopia/password)"
-export KOPIA_PASSWORD="${REPOSITORY_PASSWORD}"
+export KOPIA_PASSWORD="${REPOSITORY_PASSWORD?REPOSITORY_PASSWORD is not set}"
 
 echo "Connecting to kopia repository..."
 [[ -f /usr/local/etc/kopia/repository.config ]] && cp /usr/local/etc/kopia/repository.config /usr/local/etc/kopia/restore.config
-docker run --rm --pull always \
-  -v /usr/local/etc/kopia:/app/config \
-  -v /var/log/kopia:/app/logs \
-  -e KOPIA_PASSWORD \
-  "${docker_args[@]}" \
-  kopia/kopia:latest repository connect "${repo_type}" \
-    "${kopia_args[@]}" \
+
+kopia "${kopia_flags[@]}" \
+  repository connect "${repo_type}" \
+    "${kopia_repo_args[@]}" \
     --config-file /app/config/restore.config \
     --override-username ncp \
     --override-hostname "restore"
@@ -47,11 +68,15 @@ echo "Done."
 snapshot_json="$(ncp-kopia snapshot list --all --json | jq ".[] | select(.id | test(\"${SNAPSHOT_ID}\"))")"
 obj_id="$(echo "${snapshot_json}" | jq -r '.rootEntry.obj')"
 obj_name="$(echo "${snapshot_json}" | jq -r '.rootEntry.name')"
+has_db="$(echo "${snapshot_json}" | jq -r '.tags."includes-db" == "yes"' || echo 'false')"
+has_files="$(echo "${snapshot_json}" | jq -r '.tags."includes-files" == "yes"' || echo 'false')"
+has_nc="$(echo "${snapshot_json}" | jq -r '.tags."includes-nextcloud" == "yes"' || echo 'false')"
+has_ncp_config="$(echo "${snapshot_json}" | jq -r '.tags."includes-ncp-config" == "yes"' || echo 'false')"
 
 trap restore_maintenance_mode EXIT
 
 save_maintenance_mode || true
-if [[ "${obj_name}" == "db" ]]
+if [[ "$has_db" == "true" ]]
 then
   echo "DB backup detected."
   if [[ -z "$data_dir" ]]
@@ -60,15 +85,9 @@ then
   else
     RESTORE_DIR="$(mktemp -d "/tmp/kopia-restore.XXXXXX")"
   fi
-  docker run --rm --pull always \
-    -v /usr/local/etc/kopia:/app/config \
-    -v /var/log/kopia:/app/logs \
-    -v "${RESTORE_DIR}:/restore" \
-    -e KOPIA_PASSWORD \
-    "${docker_args[@]}" \
-    kopia/kopia:latest snapshot restore \
-      --config-file /app/config/restore.config \
-      "${obj_id}" "/restore"
+  kopia "${kopia_flags[@]}" \
+    snapshot restore \
+      "${obj_id}/nextcloud-sqlbkp.sql" "${RESTORE_DIR}/nextcloud-sqlbkp.sql"
   cd "${RESTORE_DIR}"
 
   cleanup() { local RET=$?; echo "Cleanup..."; rm -rf "${RESTORE_DIR}" || true; restore_maintenance_mode; trap "" EXIT; exit $RET; }
@@ -83,42 +102,92 @@ CREATE USER '$DBADMIN'@'localhost' IDENTIFIED BY '$DBPASSWD';
 GRANT ALL PRIVILEGES ON nextcloud.* TO $DBADMIN@localhost;
 EXIT
 EOFMYSQL
-  mysql -u root nextcloud <  "$RESTORE_DIR"/nextcloud-sqlbkp_*.bak || { echo "Error restoring nextcloud database"; return 1; }
+  mysql -u root nextcloud <  "$RESTORE_DIR"/nextcloud-sqlbkp.sql || { echo "Error restoring nextcloud database"; return 1; }
   echo "Successfully restored database from backup."
-  return
-elif [[ "${obj_name}" == "ncdata" ]]
-then
-  echo "Data backup detected"
-  [[ -e "$data_dir" ]] && {
-    bk_target="$data_dir-$( date '+%FT%s' )"
-    echo "backing up existing $data_dir to ${bk_target}..."
-    mv "$data_dir" "${bk_target}" || exit 1
-  }
-  echo "restore datadir to $data_dir"
+fi
 
-  mkdir -p "$data_dir"
-  grep -q "btrfs" <(stat -fc%T "$data_dir") && which btrfs &>/dev/null && {
-    rmdir "$data_dir"                  || exit 1
-    btrfs subvolume create "$data_dir" || exit 1
+if [[ "$has_files" == "true" ]]
+then
+  echo "Files backup detected"
+  subvol_dir="$(dirname "$data_dir")"
+  [[ -e "$subvol_dir" ]] && {
+    bk_target="$subvol_dir-$( date '+%FT%s' )"
+    echo "backing up existing $subvol_dir to ${bk_target}..."
+    mv "$subvol_dir" "${bk_target}" || exit 1
   }
-  chown www-data: "$data_dir"
+  echo "restore datadir to $subvol_dir"
+
+  mkdir -p "$subvol_dir"
+  grep -q "btrfs" <(stat -fc%T "$subvol_dir") && which btrfs &>/dev/null && {
+    rmdir "$subvol_dir"                  || exit 1
+    btrfs subvolume create "$subvol_dir" || exit 1
+  }
+  chown www-data: "$subvol_dir"
 
   cleanup() { RET=$?; echo "Cleanup..."; restore_maintenance_mode; trap "" EXIT; exit $RET; }
   trap cleanup INT TERM HUP ERR EXIT
 
   echo "Restoring files..."
-  docker run --rm --pull always \
-    -v /usr/local/etc/kopia:/app/config \
-    -v /var/log/kopia:/app/logs \
-    -v "${data_dir}:/restore" \
-    -e KOPIA_PASSWORD \
-    "${docker_args[@]}" \
-    kopia/kopia:latest snapshot restore \
+  kopia "${kopia_flags[@]}" \
+    snapshot restore \
       --config-file /app/config/restore.config \
-      "${obj_id}" "/restore"
-  echo "Snapshot restored sucessfully"
+      "${obj_id}/ncdata" "${subvol_dir}"
+  echo "Files restored sucessfully"
   exit
-else
-  echo "Invalid snapshot (Expected snapshot of /ncdata or /db, was '${obj_name}')!"
-  exit 1
 fi
+
+if [[ "$has_nc" == "true" ]]
+then
+  echo "Nextcloud backup detected"
+  [[ -e "/var/www/nextcloud" ]] && {
+    bkp_target="/var/www/kopia-restore-nextcloud-$(date -Iseconds).tar.gz"
+    bkp_target="${bkp_target/+00:00/}"
+    bkp_target="${bkp_target//:/-}"
+    echo "Backing up current nextcloud directory to "
+    tar -caf "$bkp_target" "/var/www/nextcloud"
+    rm -rf /var/www/nextcloud
+  }
+  echo "Restore nextcloud to /var/www/nextcloud"
+  mkdir -p /var/www/nextcloud
+  kopia "${kopia_flags[@]}" \
+    snapshot restore \
+      --config-file /app/config/restore.config \
+      "${obj_id}/nextcloud" "/var/www/nextcloud"
+  chown -R www-data:www-data /var/www/nextcloud
+  sed -i "s|'datadirectory' =>.*|'datadirectory' => '${data_dir}',|" /var/www/nextcloud/config/config.php
+  # Just in case we moved the opcache dir
+  install_template "php/opcache.ini.sh" "/etc/php/${PHPVER}/mods-available/opcache.ini"
+
+  # tmp upload dir
+  mkdir -p "$data_dir/tmp"
+  chown www-data: "$data_dir/tmp"
+  ncc config:system:set tempdirectory --value "$data_dir/tmp"
+  sed -i "s|^;\?upload_tmp_dir =.*$|upload_tmp_dir = $data_dir/tmp|" "/etc/php/${PHPVER}/cli/php.ini"
+  sed -i "s|^;\?upload_tmp_dir =.*$|upload_tmp_dir = $data_dir/tmp|" "/etc/php/${PHPVER}/fpm/php.ini"
+  sed -i "s|^;\?sys_temp_dir =.*$|sys_temp_dir = $data_dir/tmp|"     "/etc/php/${PHPVER}/fpm/php.ini"
+
+  # logs
+  ncc config:system:set logfile --value="${data_dir}/nextcloud.log"
+
+  # update fail2ban logpath
+  [[ -f /etc/fail2ban/jail.conf ]] && {
+    sed -i "s|logpath  =.*|logpath  = ${data_dir}/nextcloud.log|" /etc/fail2ban/jail.conf
+    pgrep fail2ban &>/dev/null && service fail2ban restart
+  }
+
+  # refresh nextcloud trusted domains
+  bash /usr/local/bin/nextcloud-domain.sh
+
+  # update the systems data-fingerprint
+  ncc maintenance:data-fingerprint
+
+  # refresh thumbnails
+  ncc files:scan-app-data
+
+  # restart PHP
+  bash -c "sleep 5; source /usr/local/etc/library.sh; clear_opcache; service php${PHPVER}-fpm restart" &>/dev/null &
+
+  echo "Nextcloud restored sucessfully"
+fi
+
+echo "Snapshot restored sucessfully"
