ncp-update: Add support for pr refs

diff --git a/bin/ncp-update b/bin/ncp-update
--- a/bin/ncp-update
+++ b/bin/ncp-update
@@ -18,6 +18,13 @@
     echo "No internet connectivity"
     exit 1
   }
+  [[ -z "$2" ]] || {
+    git fetch origin "$2" || {
+      echo "Error: Could not fetch $2"
+      exit 1
+    }
+    git checkout FETCH_HEAD
+  }
 
   [[ -f /.ncp-image ]] || cd "$TMPDIR"         # update locally during build
 
