࿓❯ I was able to make it a bit smaller
Signed-off-by: Zendai Owl <12261439+ZendaiOwl@users.noreply.github.com>

diff --git a/bin/ncp-diag b/bin/ncp-diag
--- a/bin/ncp-diag
+++ b/bin/ncp-diag
@@ -62,20 +62,19 @@ echo "HPB service|$( ncc notify_push:self-test &>/dev/null && echo up || echo do
 echo "Postfix service|$( pgrep -fc postfix &>/dev/null && echo up || echo down )"
 
 # WAN
-echo "internet check|$( ping -W 2 -w 1 -q github.com &>/dev/null && echo ok || echo no )"
+echo "Internet check|$( ping -W 2 -w 1 -q github.com &>/dev/null && echo ok || echo no )"
 
 function is_port_open()
 {
   local port port_url ip_url tmp_file token token_args grep_token grep_portcheck \
-  public_ipv4 ipv4_check_fail ipv4_port_access ipv4_args ipv4_portcheck_args \
-  public_ipv6 ipv6_check_fail ipv6_port_access ipv6_args ipv6_portcheck_args
+  publicIPv4 publicIPv4_exist ipv4_port_access ipv4_args ipv4_portcheck_args \
+  publicIPv6 publicIPv6_exist ipv6_port_access ipv6_args ipv6_portcheck_args
   tmp_file=$(mktemp)
   trap "rm -rf ${tmp_file}; exit $?" EXIT ERR SIGINT SIGQUIT SIGABRT SIGTERM SIGHUP
   
     port="$1"
-    ipv4_check_fail=false
-    ipv6_check_fail=false
-    
+    publicIPv4_exist=True
+    publicIPv6_exist=True
     readonly port_url="https://portchecker.co"
     readonly ip_url="https://icanhazip.com"
     readonly token_args=(-T2 -t1 -qO- --keep-session-cookies --save-cookies "${tmp_file}" "${port_url}")
@@ -84,53 +83,70 @@ function is_port_open()
     readonly ipv4_args=(-s -m4 -4 "${ip_url}")
     readonly ipv6_args=(-s -m4 -6 "${ip_url}")
   
-    public_ipv4=$(curl "${ipv4_args[@]}" 2>/dev/null) || { ipv4_check_fail=:; }
-    public_ipv6=$(curl "${ipv6_args[@]}" 2>/dev/null) || { ipv6_check_fail=:; }
+    publicIPv4=$(curl "${ipv4_args[@]}" 2>/dev/null) || { publicIPv4_exist=False; }
+    publicIPv6=$(curl "${ipv6_args[@]}" 2>/dev/null) || { publicIPv6_exist=False; }
   
-    if [[ "${ipv4_check_fail}" == true ]] && [[ "${ipv6_check_fail}" == true ]]
+    if [[ "${publicIPv4_exist}" == False ]] && [[ "${publicIPv6_exist}" == False ]]
     then
-      echo "Error - IPv4 & IPv6: N/A, couldn't get external IP."; return 1;
+      echo "Error - IPv4 & IPv6: Couldn't get public IP."
+      return 1
     fi
 
     token=$(wget "${token_args[@]}" | grep "${grep_token_args[@]}" )
-    readonly ipv4_portcheck_args=(-T2 -t1 -qO- --load-cookies "${tmp_file}" "${port_url}" --post-data "target_ip=${public_ipv4}&port=${port}&_csrf=${token::-1}")
-    readonly ipv6_portcheck_args=(-T2 -t1 -qO- --load-cookies "${tmp_file}" "${port_url}" --post-data "target_ip=${public_ipv6}&port=${port}&_csrf=${token::-1}")
+    readonly ipv4_portcheck_args=(-T2 -t1 -qO- --load-cookies "${tmp_file}" "${port_url}" --post-data "target_ip=${publicIPv4}&port=${port}&_csrf=${token::-1}")
+    readonly ipv6_portcheck_args=(-T2 -t1 -qO- --load-cookies "${tmp_file}" "${port_url}" --post-data "target_ip=${publicIPv6}&port=${port}&_csrf=${token::-1}")
   
     if [[ -n "${token}" ]]
     then
-      if [[ "${ipv4_check_fail}" == false ]] && [[ "${ipv6_check_fail}" == true ]]
+      if [[ "${publicIPv4_exist}" == True ]] && [[ "${publicIPv6_exist}" == False ]]
       then
         grep "${grep_portcheck_args[@]}" <(wget "${ipv4_portcheck_args[@]}") && \
-        { echo "Open IPv4 (IPv6: N/A)"; return 0; } || { echo "Closed IPv4 (IPv6: N/A)"; return 0; }
-      elif [[ "${ipv4_check_fail}" == true ]] && [[ "${ipv6_check_fail}" == false ]]
+        { ipv4_port_access=True; } || { ipv4_port_access=False; }
+      elif [[ "${publicIPv4_exist}" == False ]] && [[ "${publicIPv6_exist}" == True ]]
       then
         grep "${grep_portcheck_args[@]}" <(wget "${ipv6_portcheck_args[@]}") && \
-        { echo "Open IPv6 (IPv4: N/A)"; return 0; } || { echo "Closed IPv6 (IPv4: N/A)"; return 0; }
+        { ipv6_port_access=True; } || { ipv6_port_access=False; }
       else
         grep "${grep_portcheck_args[@]}" <(wget "${ipv4_portcheck_args[@]}") && \
-        { ipv4_port_access=true; } || { ipv4_port_access=false; }
+        { ipv4_port_access=True; } || { ipv4_port_access=False; }
   
         grep "${grep_portcheck_args[@]}" <(wget "${ipv6_portcheck_args[@]}") && \
-        { ipv6_port_access=true; } || { ipv6_port_access=false; }
-  
-        if [[ "${ipv4_port_access}" == true ]] && [[ "${ipv6_port_access}" == true ]]
-        then
-          echo "Open IPv4 & IPv6"
-          return 0
-        fi
-        if [[ "${ipv4_port_access}" == true ]] && [[ "${ipv6_port_access}" == false ]]
-        then
-          echo "Open IPv4 (IPv6: Closed)"
-          return 0
-        elif [[ "${ipv4_port_access}" == false ]] && [[ "${ipv6_port_access}" == true ]]
-        then
-          echo "Open IPv6 (IPv4: Closed)"
-          return 0
-        else
-          echo "Closed IPv4 & IPv6"
-          return 1
-        fi
+        { ipv6_port_access=True; } || { ipv6_port_access=False; }
       fi
+       
+      if [[ "${ipv4_port_access}" == True ]] && [[ "${ipv6_port_access}" == True ]]
+      then
+        echo "Open. IPv4: ${ipv4_port_access} & IPv6: ${ipv6_port_access}"
+        return 0
+      elif [[ "${ipv4_port_access}" == False ]] && [[ "${ipv6_port_access}" == False ]]
+      then
+        echo "Closed. IPv4 & IPv6"
+        return 0
+      fi
+      
+      if [[ "${ipv4_port_access}" == True ]] && [[ "${publicIPv6_exist}" == False  ]]
+      then
+        echo "Open. IPv4: ${ipv4_port_access} & IPv6: N/A" 
+        return 0
+      elif [[ "${ipv6_port_access}" == True ]] && [[ "${publicIPv4_exist}" == False  ]]
+      then
+        echo "Open. IPv6: ${ipv6_port_access} & IPv4: N/A"
+        return 0
+      fi
+      
+      if [[ "${ipv4_port_access}" == True ]] && [[ "${ipv6_port_access}" == False ]]
+      then
+        echo "Open. IPv4: ${ipv4_port_access} & IPv6: ${ipv6_port_access}"
+        return 0
+      elif [[ "${ipv4_port_access}" == False ]] && [[ "${ipv6_port_access}" == True ]]
+      then
+        echo "Open. IPv4: ${ipv4_port_access} & IPv6: ${ipv6_port_access}"
+        return 0
+      else
+        echo "Error - Teapot"
+        return 1
+      fi
+      
     else
       echo "Error - Couldn't obtain a token for port check"
       return 1
@@ -147,8 +163,8 @@ GW=$(    ip r | grep "default via" | awk '{ print $3 }' | head -1 )
 IP="$(get_ip)"
 
 echo "IP|$IP"
-echo "gateway|$GW"
-echo "interface|$IFACE"
+echo "Gateway|$GW"
+echo "Interface|$IFACE"
 
 # Certificates
 CERTS="$( grep "SSLCertificateFile */etc/letsencrypt/live/" /etc/apache2/sites-available/nextcloud.conf \
@@ -160,7 +176,7 @@ RESOLV="$( ping -c1 -w1 "$CERTS" 2>/dev/null | head -1 | grep -oP '\d{1,3}(.\d{1
 echo "NAT loopback|$( [[ "$RESOLV" == "$IP" ]] && echo yes || echo no )"
 
 # Other
-echo "uptime|$( uptime | cut -f1 -d',' | awk '{ $1=""; $2=""; print }' | tr -d "  " )"
+echo "Uptime|$( uptime | cut -f1 -d',' | awk '{ $1=""; $2=""; print }' | tr -d "  " )"
 # Get kernel version
 
 # License
