ncp-config: silence connectivity errors

diff --git a/bin/ncp-check-version b/bin/ncp-check-version
--- a/bin/ncp-check-version
+++ b/bin/ncp-check-version
@@ -6,7 +6,7 @@ TMPDIR="$( mktemp -d /tmp/ncp-check.XXXXXX || ( echo "Failed to create temp dir.
 trap "rm -rf \"${TMPDIR}\"; exit 0" 0 1 2 3 15
 
 git clone --depth 20 -q --bare https://github.com/nextcloud/nextcloudpi.git "$TMPDIR" || {
-  echo "The git clone command failed: No connectivity to https://github.com ?"
+  echo "The git clone command failed: No connectivity to https://github.com ?" >&2
   exit 1
 }
 
