ncp-update: Fetch complete git history if tag not in last 20 commits
Signed-off-by: Tobias K <6317548+theCalcaholic@users.noreply.github.com>

diff --git a/bin/ncp-update b/bin/ncp-update
--- a/bin/ncp-update
+++ b/bin/ncp-update
@@ -23,10 +23,11 @@
   ./update.sh || exit $?
 
   cd "$TMPDIR"
+  git describe --always --tags --abbrev=0 > /dev/null 2>&1 || git fetch --unshallow
   VER=$( git describe --always --tags --abbrev=0 | grep -oP "v\d+\.\d+\.\d+" )
 
   # check format
-  grep -qP "v\d+\.\d+\.\d+" <<< "$VER" || { echo "Error: missing or invalid version (was '$VER')"; exit 1; }
+  grep -qP "v\d+\.\d+\.\d+" <<< "$VER" || { echo "Error: missing or invalid version"; exit 1; }
 
   echo "$VER" > /usr/local/etc/ncp-version
   echo "$VER" > /var/run/.ncp-latest-version
