avoid temp dir vulnerabilities

diff --git a/bin/ncp-check-version b/bin/ncp-check-version
--- a/bin/ncp-check-version
+++ b/bin/ncp-check-version
@@ -2,14 +2,15 @@
 
 # update latest available version in /var/run/.ncp-latest-version
 
-rm -rf /tmp/ncp-check-tmp
+TMPDIR="$( mktemp -d /tmp/ncp-check.XXXXXX || ( echo "Failed to create temp dir. Exiting" >&2; exit 1 ) )"
+trap "rm -rf \"${TMPDIR}\"; exit 0" 0 1 2 3 15
 
-git clone --depth 20 -q --bare https://github.com/nextcloud/nextcloudpi.git /tmp/ncp-check-tmp || {
+git clone --depth 20 -q --bare https://github.com/nextcloud/nextcloudpi.git "$TMPDIR" || {
   echo "The git clone command failed: No connectivity to https://github.com ?"
   exit 1
 }
 
-cd /tmp/ncp-check-tmp || exit 1
+cd "$TMPDIR" || exit 1
 VER=$( git describe --always --tags | grep -oP "v\d+\.\d+\.\d+" )
 grep -qP "v\d+\.\d+\.\d+" <<< "$VER" && {       # check format
   echo "$VER" > /var/run/.ncp-latest-version
@@ -22,5 +23,3 @@ grep -qP "v\d+\.\d+\.\d+" <<< "$VER" && {       # check format
     sed 's|* \[tag: |[|' > /usr/local/etc/ncp-changelog
 }
 cd / || exit 1
-
-rm -rf /tmp/ncp-check-tmp
