nc-autoupdate-nc: Fix erroneous update/updated notifications
Signed-off-by: Tobias Knöppler <6317548+theCalcaholic@users.noreply.github.com>

diff --git a/bin/ncp-update-nc b/bin/ncp-update-nc
--- a/bin/ncp-update-nc
+++ b/bin/ncp-update-nc
@@ -26,19 +26,19 @@ VER="$1"
 connect_to_nc_update() {
   tail -n 100 -f "/var/log/ncp-update-nc.log" &
   tail_pid=$!
+  trap "kill '$tail_pid'" EXIT
   while [[ "$(systemctl is-active ncp-update-nc ||:)" =~ ^(active|activating|deactivating)$ ]]
   do
     sleep 3
   done
 
-  kill "$tail_pid"
   if [[ "$(systemctl is-active ncp-update-nc ||:)" == "inactive" ]]
   then
     echo "Nextcloud update finished successfully."
     return 0
   elif [[ "$(systemctl is-active ncp-update-nc ||:)" == "failed" ]]
   then
-    echo "Nextcloud update failed."
+    echo "Nextcloud update failed (or was installed already)."
     return 1
   else
     echo "Nextcloud update was not found or failed (unexpected status: '$(systemctl is-active ncp-update-nc ||:)')"
@@ -52,15 +52,16 @@ then
   exit $?
 fi
 
-systemctl reset-failed ncp-encrypt ||:
-systemd-run -u 'ncp-update-nc' bash -c "DBG='${DBG:-}' /usr/local/bin/ncp-update-nc.d/update-nc.sh '${VER}' |& tee /var/log/ncp-update-nc.log"
-sleep 5
+systemctl reset-failed ncp-encrypt 2>/dev/null ||:
+systemd-run -u 'ncp-update-nc' bash -c "set -o pipefail; DBG='${DBG:-}' /usr/local/bin/ncp-update-nc.d/update-nc.sh '${VER}' |& tee /var/log/ncp-update-nc.log"
+sleep 1
 
 if ! [[ "$(systemctl is-active ncp-update-nc ||:)" =~ ^(active|inactive|activating|deactivating)$ ]]
 then
   echo "Failed to start ncp-update-nc"
   [[ -f /var/log/ncp-update-nc.log ]] && cat /var/log/ncp-update-nc.log
   systemctl status --no-pager ncp-update-nc ||:
+  exit 1
 fi
 
 connect_to_nc_update
