ncp-update: Add support for PRs
Signed-off-by: Tobias Knöppler <6317548+theCalcaholic@users.noreply.github.com>

diff --git a/bin/ncp-update b/bin/ncp-update
--- a/bin/ncp-update
+++ b/bin/ncp-update
@@ -19,6 +19,14 @@
     exit 1
   }
 
+  [[ -z "$2" ]] || {
+    git fetch origin "$2" || {
+      echo "Error: Could not fetch $2"
+      exit 1
+    }
+    git checkout FETCH_HEAD
+  } 
+
   [[ -f /.ncp-image ]] || cd "$TMPDIR"         # update locally during build
 
   echo -e "Performing updates"
