Rename TMPDIR environment variables to TEMPDIR to avoid overriding php temp dir.
Signed-off-by: Tobias Knöppler <6317548+theCalcaholic@users.noreply.github.com>

diff --git a/bin/ncp-restore b/bin/ncp-restore
--- a/bin/ncp-restore
+++ b/bin/ncp-restore
@@ -16,32 +16,32 @@ DIR="$( cd "$( dirname "$BACKUPFILE" )" &>/dev/null && pwd )" #abspath
 [[ -f "$BACKUPFILE"   ]] || { echo "$BACKUPFILE not found"          ; exit 1; }
 [[ "$DIR" =~ "$NCDIR".* ]] && { echo "Refusing to restore from $NCDIR"; exit 1; }
 
-TMPDIR="$( mktemp -d "$( dirname "$BACKUPFILE" )"/ncp-restore.XXXXXX )" || { echo "Failed to create temp dir" >&2; exit 1; }
-[[ "$(stat -fc%T "${TMPDIR}")" =~ ext|btrfs|zfs ]] || { echo "Can only restore from ext/btrfs/zfs filesystems (found '$(stat -fc%T "${TMPDIR}")"     >&2; exit 1; }
+TEMPDIR="$( mktemp -d "$( dirname "$BACKUPFILE" )"/ncp-restore.XXXXXX )" || { echo "Failed to create temp dir" >&2; exit 1; }
+[[ "$(stat -fc%T "${TEMPDIR}")" =~ ext|btrfs|zfs ]] || { echo "Can only restore from ext/btrfs/zfs filesystems (found '$(stat -fc%T "${TEMPDIR}")"     >&2; exit 1; }
 
-TMPDIR="$( cd "$TMPDIR" &>/dev/null && pwd )" || { echo "$TMPDIR not found"; exit 1; } #abspath
-cleanup(){  local RET=$?; echo "Cleanup..."; rm -rf "${TMPDIR}"; trap "" EXIT; exit $RET; }
+TEMPDIR="$( cd "$TEMPDIR" &>/dev/null && pwd )" || { echo "$TEMPDIR not found"; exit 1; } #abspath
+cleanup(){  local RET=$?; echo "Cleanup..."; rm -rf "${TEMPDIR}"; trap "" EXIT; exit $RET; }
 trap cleanup INT TERM HUP ERR EXIT
-rm -rf "$TMPDIR" && mkdir -p "$TMPDIR"
+rm -rf "$TEMPDIR" && mkdir -p "$TEMPDIR"
 
 [[ "$BACKUPFILE" =~ .*".tar.gz" ]] && compress_arg="-I pigz"
 
-# CHECK FREE SPACE IN $TMPDIR
+# CHECK FREE SPACE IN $TEMPDIR
 echo "check free space..." # allow at least ~100 extra MiB
 extractedsize=$(tar $compress_arg -tvf "$BACKUPFILE" | awk '{s+=$3} END{printf "%.0f", (s/1024)}') # Size of extracted files in "KB"
 size=$(($extractedsize + 100*1024))
-free=$( df "$TMPDIR" | tail -1 | awk '{ print $4 }' )
+free=$( df "$TEMPDIR" | tail -1 | awk '{ print $4 }' )
 [ $size -ge $free ] && {
-  echo "free space check failed. Need $size KB in $TMPDIR";
+  echo "free space check failed. Need $size KB in $TEMPDIR";
   exit 1;
 }
 
 # EXTRACT FILES
 echo "extracting backup file $BACKUPFILE..."
-tar $compress_arg -xf "$BACKUPFILE" -C "$TMPDIR" || exit 1
+tar $compress_arg -xf "$BACKUPFILE" -C "$TEMPDIR" || exit 1
 
 ## SANITY CHECKS
-[[ -d "$TMPDIR"/nextcloud ]] && [[ -f "$( ls "$TMPDIR"/nextcloud-sqlbkp_*.bak 2>/dev/null )" ]] || {
+[[ -d "$TEMPDIR"/nextcloud ]] && [[ -f "$( ls "$TEMPDIR"/nextcloud-sqlbkp_*.bak 2>/dev/null )" ]] || {
   echo "invalid backup file. Abort"
   exit 1
 }
@@ -54,7 +54,7 @@ echo "restore files..."
   mv -T "$NCDIR/data" "$DATA_BKP_DIR/"
 }
 rm -rf "$NCDIR"
-mv -T "$TMPDIR"/nextcloud "$NCDIR" || { echo "Error restoring base files"; exit 1; }
+mv -T "$TEMPDIR"/nextcloud "$NCDIR" || { echo "Error restoring base files"; exit 1; }
 
 if [[ -n "$DATA_BKP_DIR" ]]
 then
@@ -91,7 +91,7 @@ EOFMYSQL
 # shellcheck disable=SC2181
 [ $? -ne 0 ] && { echo "Error configuring nextcloud database"; exit 1; }
 
-mysql -u root nextcloud <  "$TMPDIR"/nextcloud-sqlbkp_*.bak || { echo "Error restoring nextcloud database"; exit 1; }
+mysql -u root nextcloud <  "$TEMPDIR"/nextcloud-sqlbkp_*.bak || { echo "Error restoring nextcloud database"; exit 1; }
 
 ## RESTORE DATADIR
 
@@ -105,7 +105,7 @@ cd "$NCDIR"
 
 ### INCLUDEDATA=yes situation
 NUMFILES=2
-if [[ $( ls "$TMPDIR" | wc -l ) -eq $NUMFILES ]]; then
+if [[ $( ls "$TEMPDIR" | wc -l ) -eq $NUMFILES ]]; then
 
   [[ -e "$DATADIR" ]] && {
     bk_target="$DATADIR-$( date '+%FT%s' )"
@@ -121,7 +121,7 @@ if [[ $( ls "$TMPDIR" | wc -l ) -eq $NUMFILES ]]; then
     btrfs subvolume create "$DATADIR" || exit 1
   }
   chown www-data: "$DATADIR"
-  TMPDATA="$TMPDIR/$( basename "$DATADIR" )"
+  TMPDATA="$TEMPDIR/$( basename "$DATADIR" )"
   mv "$TMPDATA"/* "$TMPDATA"/.[!.]* "$DATADIR" || exit 1
   rmdir "$TMPDATA"                             || exit 1
 
