nc-previews.sh, 1.57.0.sh: Run preview generation in background, avoid running migration to new preview setup more than once

diff --git a/etc/ncp-templates/cron.hourly/ncp-previewgenerator b/etc/ncp-templates/cron.hourly/ncp-previewgenerator
--- a/etc/ncp-templates/cron.hourly/ncp-previewgenerator
+++ b/etc/ncp-templates/cron.hourly/ncp-previewgenerator
@@ -1,6 +1,14 @@
 #!/usr/bin/env bash
 
 cat <<'EOF'
+GENERATE_JOB_ID="ncp-generate-previews"
+
+if [[ "$(systemctl is-active "${GENERATE_JOB_ID}" ||:)" =~ ^(active|activating|deactivating)$ ]]
+then
+  echo "Existing initial preview generation process detected. Aborting..."
+  exit 0
+fi
+
 #!/usr/bin/env bash
 set -eu
 source /usr/local/etc/library.sh
@@ -13,7 +21,7 @@ else
 fi
 
 for _ in $(seq 1 $(nproc)); do
-  ncc preview:generate-all -n -q &
+  ncc preview:pre-generate -n -q &
 done
 
 wait
