nc-init.sh, 020nextcloud, ncp.sh: Workaround network related bugs when running cross-architecture using qemu

diff --git a/docker/nextcloud/020nextcloud b/docker/nextcloud/020nextcloud
--- a/docker/nextcloud/020nextcloud
+++ b/docker/nextcloud/020nextcloud
@@ -37,7 +37,11 @@ postfix start
 test -f /data/nextcloud/config/config.php || {
   echo "Uninitialized instance, running nc-init..."
   source /usr/local/etc/library.sh
-  run_app_unsafe /nc-init.sh
+  run_app_unsafe /nc-init.sh || {
+    echo "Something went wrong while initializing nextcloud. Aborting...";
+    rm /data/nextcloud/config/config.php;
+    exit 1;
+  }
   mv /index.php /var/www/nextcloud/    # restore this file after init
 }
 
@@ -58,8 +62,9 @@ EXIT
 EOF
 
 # Trusted Domain ( local IP )
-IFACE=$( ip r | grep "default via" | awk '{ print $5 }' | head -1 )
-IP=$( ip a show dev "$IFACE" | grep global | grep -oP '\d{1,3}(.\d{1,3}){3}' | head -1 )
+# IFACE=$( ip r | grep "default via" | awk '{ print $5 }' | head -1 )
+# IP=$( ip a show dev "$IFACE" | grep global | grep -oP '\d{1,3}(.\d{1,3}){3}' | head -1 )
+IP="$(get_internal_ip)"
 ncc config:system:set trusted_domains 1 --value="$IP"
 
 # Trusted Domain ( as an argument )
