Update build-lxd.yml
Signed-off-by: Tobias Knöppler <6317548+theCalcaholic@users.noreply.github.com>

diff --git a/.github/workflows/build-lxd.yml b/.github/workflows/build-lxd.yml
--- a/.github/workflows/build-lxd.yml
+++ b/.github/workflows/build-lxd.yml
@@ -533,8 +533,23 @@ jobs:
           then
             echo "Nextcloud is up to date - skipping NC update test."
           else
+            for i in {1..10};
+            do
+            echo "running nc update ($i/10)..."
             sudo "$LXC" exec ncp -- bash -c "DBG=x ncp-update-nc ${latest_nc_version?}"
+            
             sudo "$LXC" exec ncp -- /usr/local/bin/ncc status
+            current_nc_version_new="$(sudo "$LXC" exec ncp -- ncc status | grep "version:" | awk '{ print $3 }')"
+            if [[ "$current_nc_version" =~ "$latest_nc_version".* ]]
+            then
+              break
+            fi
+            if [[ "$current_nc_version" == "$current_nc_version_new" ]]
+            then
+              echo "failed to update to $latest_version”
+              exit 1
+            fi
+            done
           fi
           
           sudo "$LXC" exec ncp -- rm -f /opt/ncdata/data/nextcloud.log
